<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="AuditApp.Package\AuditApp.Package.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Models\**\*.cs" />
    <Compile Remove="Services\**\*.cs" />
    <Compile Remove="AuditApp.Package\**\*.cs" />
  </ItemGroup>

</Project>
